### ISSUE TITLE
S3 support?

### ISSUE THREAD

**Issue by sander-tjuna** [jeylabs/vaultbox#1]
Hello, I got this awesome file manager working with Amazon aws. It uploads the pictures to the bucket but when returning the url anywhere (like editor) it tries to get a local url. I have tried searching for where the url is made but can't seem to find it.

**Comment by sasureshkumar** [comment]
@sander-tjuna Resolved in 2.0.1 please update and check.

**Comment by sander-tjuna** [comment]
Thank you, this works great. Although the image cropper does not work yet, neither on s3 or local.

EDIT: Will create new issue report.
